version: "3.8"

services:
    roo-cli:
        image: roo-cli:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: roo-cli
        volumes:
            - ${WORKSPACE_PATH:-./workspace}:/workspace
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY:-}
            - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
            - OPENAI_MODEL_ID=${OPENAI_MODEL_ID:-}
            - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
            - ANTHROPIC_MODEL_ID=${ANTHROPIC_MODEL_ID:-}
        ports:
            - "3000:3000" # 为 MCP 服务器暴露端口
        # 设置工作目录为应用程序目录
        working_dir: /app
        # 默认命令可以在运行时覆盖
        command: --help
